### ISSUE TITLE
Create a Basic Working Website

### ISSUE THREAD

**Issue by vincekyi** [UCLA-BD2K/bd2kcrawler#2]
As a developer, I would like to have a basic working website set up locally.

**Comment by almgong** [comment]
The website will be simple, featuring a login and a dashboard to search for crawl results (updates to news and/or publications).

**Comment by almgong** [comment]
Next Tasks:

Login: 
- want to complete the implementation with spring-security-web package - for user authentication

Dashboard (where one can see archived results of the crawler):
- wants: 
  - Create dropdown for each site (LINCS-DCIC, etc.) to help navigate results
  - Add radio buttons to filter by publications vs news

*Result page:
- Want a page that displays a comprehensive summary of diffs, etc. for a given record/page

**Comment by almgong** [comment]
Basic site with most important parts is now live in the repo.
