### ISSUE TITLE
Setup MongoDB

### ISSUE THREAD

**Issue by vincekyi** [UCLA-BD2K/bd2kcrawler#3]
As a developer, I would like to have a Mongo database setup to store the data from the crawler.

**Comment by almgong** [comment]
Mongo configuration:

The database will be run on localhost:27017. It is expected to have the name: BD2KCrawlerDB.

2 Collections used so far:

Pages (contains archives of the previously crawled pages)
{
_id: auto,
lastCrawlTime: "yyyy-mm-dd hh:mm:ss",
lastDiff: "...json string representation of the last digest result",
content: "string content returned by crawler",
url: "string url of the page this record refers to",
pageID: "e.g. LINCS-DCIC"
}

Users
{
id_: auto,
firstName: "string",
lastName: "string",
username: "string",
password: "string store a one way hash here",
email: "string"
}

**Comment by almgong** [comment]
Current collection structure:

Pages (contains archives of the previously crawled pages) **added previous crawl content (good to have in case we want to change presentation of the results page), and finalize on format of the diff representation, simple html string is good enough - we have both strings to generate a diff list if needed anyways**
{
_id: auto,
lastCrawlTime: "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
lastDiff: "prettyHtml, generated by diff library",
previousCrawlContent: "string representation of results from previous crawl"
currentContent: "string content returned by crawler on the most recent run",
url: "string url of the page this record refers to",
centerID: "e.g. LINCS-DCIC"
}

Users **removed username, use email instead**
{
id_: auto,
firstName: "string",
lastName: "string",
password: "string store a one way hash here",
email: "string"
}

Centers **NEW, to hold information on BD2KCenters; numerous components of app require knowledge of this**
{
id_:auto
centerID: "e.g. LINCS-DCIC",
grant: "...",
siteURL: "< the base url of the site this center is associated with, should == the seedURL for crawling >"
}

**Comment by almgong** [comment]
**Removed previousCrawlContent**

I now see that it was unnecessary.

**Comment by almgong** [comment]
**Add**

Added a "role" field to Users collection. This is for authentication, and by default is "ROLE_USER".

For now, ROLE_ADMIN and ROLE_USER will be the only roles.

ROLE_ADMIN: all access, can initiate crawls
ROLE_USER: can access dashboard and results of crawls.

**Comment by almgong** [comment]
**Added a PublicationsResults collection**

//unused as a collection, but re-purposed as a nested object in PublicationResults
Publication {
title: string,
pmid: string,
pubDate: string,
authors: [array of string],
journal: string
}

PublicationResults
{
_id:auto,
centerID: string id (LINCS-DCIC)
lastCrawlTime: stirng,
currentContent: [array of string pmids],
lastDiff: [array of string pmids],
fullContent: [array of Publication]
}

**Comment by almgong** [comment]
No more modifications to DB "schema" needed. All levels of the app including database storage/access is working in unison and as expected.
